# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuestBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GuestBook
  pod 'mailcore2-ios'

  target 'GuestBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GuestBook-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GuestBook-tvOS

  target 'GuestBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
